/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp/webhook'
import { Route as AuthenticatedAppWhatsappRouteImport } from './routes/_authenticated/app.whatsapp'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app.relatorios'
import { Route as AuthenticatedAppReceitasRouteImport } from './routes/_authenticated/app.receitas'
import { Route as AuthenticatedAppMetasRouteImport } from './routes/_authenticated/app.metas'
import { Route as AuthenticatedAppInvestimentosRouteImport } from './routes/_authenticated/app.investimentos'
import { Route as AuthenticatedAppDespesasRouteImport } from './routes/_authenticated/app.despesas'
import { Route as AuthenticatedAppAssistenteRouteImport } from './routes/_authenticated/app.assistente'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp/webhook',
  path: '/api/whatsapp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWhatsappRoute =
  AuthenticatedAppWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReceitasRoute =
  AuthenticatedAppReceitasRouteImport.update({
    id: '/receitas',
    path: '/receitas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMetasRoute = AuthenticatedAppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInvestimentosRoute =
  AuthenticatedAppInvestimentosRouteImport.update({
    id: '/investimentos',
    path: '/investimentos',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDespesasRoute =
  AuthenticatedAppDespesasRouteImport.update({
    id: '/despesas',
    path: '/despesas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAssistenteRoute =
  AuthenticatedAppAssistenteRouteImport.update({
    id: '/assistente',
    path: '/assistente',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/assistente': typeof AuthenticatedAppAssistenteRoute
  '/app/despesas': typeof AuthenticatedAppDespesasRoute
  '/app/investimentos': typeof AuthenticatedAppInvestimentosRoute
  '/app/metas': typeof AuthenticatedAppMetasRoute
  '/app/receitas': typeof AuthenticatedAppReceitasRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/app/assistente': typeof AuthenticatedAppAssistenteRoute
  '/app/despesas': typeof AuthenticatedAppDespesasRoute
  '/app/investimentos': typeof AuthenticatedAppInvestimentosRoute
  '/app/metas': typeof AuthenticatedAppMetasRoute
  '/app/receitas': typeof AuthenticatedAppReceitasRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/assistente': typeof AuthenticatedAppAssistenteRoute
  '/_authenticated/app/despesas': typeof AuthenticatedAppDespesasRoute
  '/_authenticated/app/investimentos': typeof AuthenticatedAppInvestimentosRoute
  '/_authenticated/app/metas': typeof AuthenticatedAppMetasRoute
  '/_authenticated/app/receitas': typeof AuthenticatedAppReceitasRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/whatsapp': typeof AuthenticatedAppWhatsappRoute
  '/api/whatsapp/webhook': typeof ApiWhatsappWebhookRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/app'
    | '/app/assistente'
    | '/app/despesas'
    | '/app/investimentos'
    | '/app/metas'
    | '/app/receitas'
    | '/app/relatorios'
    | '/app/whatsapp'
    | '/api/whatsapp/webhook'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/app/assistente'
    | '/app/despesas'
    | '/app/investimentos'
    | '/app/metas'
    | '/app/receitas'
    | '/app/relatorios'
    | '/app/whatsapp'
    | '/api/whatsapp/webhook'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/app'
    | '/_authenticated/app/assistente'
    | '/_authenticated/app/despesas'
    | '/_authenticated/app/investimentos'
    | '/_authenticated/app/metas'
    | '/_authenticated/app/receitas'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/whatsapp'
    | '/api/whatsapp/webhook'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/whatsapp/webhook': {
      id: '/api/whatsapp/webhook'
      path: '/api/whatsapp/webhook'
      fullPath: '/api/whatsapp/webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/whatsapp': {
      id: '/_authenticated/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AuthenticatedAppWhatsappRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/receitas': {
      id: '/_authenticated/app/receitas'
      path: '/receitas'
      fullPath: '/app/receitas'
      preLoaderRoute: typeof AuthenticatedAppReceitasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/metas': {
      id: '/_authenticated/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AuthenticatedAppMetasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/investimentos': {
      id: '/_authenticated/app/investimentos'
      path: '/investimentos'
      fullPath: '/app/investimentos'
      preLoaderRoute: typeof AuthenticatedAppInvestimentosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/despesas': {
      id: '/_authenticated/app/despesas'
      path: '/despesas'
      fullPath: '/app/despesas'
      preLoaderRoute: typeof AuthenticatedAppDespesasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assistente': {
      id: '/_authenticated/app/assistente'
      path: '/assistente'
      fullPath: '/app/assistente'
      preLoaderRoute: typeof AuthenticatedAppAssistenteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssistenteRoute: typeof AuthenticatedAppAssistenteRoute
  AuthenticatedAppDespesasRoute: typeof AuthenticatedAppDespesasRoute
  AuthenticatedAppInvestimentosRoute: typeof AuthenticatedAppInvestimentosRoute
  AuthenticatedAppMetasRoute: typeof AuthenticatedAppMetasRoute
  AuthenticatedAppReceitasRoute: typeof AuthenticatedAppReceitasRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppWhatsappRoute: typeof AuthenticatedAppWhatsappRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssistenteRoute: AuthenticatedAppAssistenteRoute,
  AuthenticatedAppDespesasRoute: AuthenticatedAppDespesasRoute,
  AuthenticatedAppInvestimentosRoute: AuthenticatedAppInvestimentosRoute,
  AuthenticatedAppMetasRoute: AuthenticatedAppMetasRoute,
  AuthenticatedAppReceitasRoute: AuthenticatedAppReceitasRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppWhatsappRoute: AuthenticatedAppWhatsappRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
